title: Hi 
author: SeraLee 
description: Hi, It's Sera's blog 

highlighter: null
permalink: /:title

url: "https://leesera.github.io/"
baseurl: "https://leesera.github.io/"

sass:
  sass_dir: public/css
  style: :compressed
